version: '3.8'

services:
  surveyor_db:
    image: postgres:12-alpine
    environment:
      "POSTGRES_USER": "postgres"
      "POSTGRES_PASSWORD": "postgres"
      "POSTGRES_DB": "surveyor_development"
      "PGDATA": "/var/lib/postgresql/data"
    ports:
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    logging:
      driver: none
    networks:
      - surveyor

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: surveyor
    container_name: surveyor
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=surveyor_db
    volumes:
      - ./surveyor:/surveyor
    restart: always
    ports:
      - 3000:3000
    links:
      - surveyor_db
    tty: true
    networks:
      - surveyor

networks:
  surveyor:
    driver: "bridge"
volumes:
  pg_data:
    name: surveyor_volume_pg
